version: "3.8"

services: 
  expenses-db:
    image: postgres:13
    ports: 
      - 5434:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: expenses
    networks:
      - app
    

networks:
  app: